### ISSUE TITLE
use TLS to connect to LDAP

### ISSUE THREAD

**Issue by Metzlmane** [kamax-io/mxisd#18]
I tried to connect without TLS, seems working.
I changed the settings to use TLS as i did for synaps, but it didn't work.
Did i miss something? I always get:
`"status":500,"error":"Internal Server Error","exception":"org.apache.directory.ldap.client.api.exception.InvalidConnectionException","message":"Cannot connect to the server: Connection refused","path":"/_matrix/identity/api/v1/lookup"}`

Can you please give me an example?

**Comment by maxidor** [comment]
I never tried with TLS so far, so I don't know yet how to configure mxisd so the LDAP library works.

I'll check it out and will let you know!

**Comment by maxidor** [comment]
I've pushed a commit that enables support for TLS via a configuration option.
Please checkout the latest code and add the `tls` config item to your config file with value `true`, [like so](https://github.com/kamax-io/mxisd/blob/master/application.example.yaml#L101)

**Comment by Metzlmane** [comment]
This works perfectly
