### ISSUE TITLE
requestToken was requested but not implemented

### ISSUE THREAD

**Issue by Kleingeldprinz** [kamax-io/mxisd#19]
Hi. My plan is to use a single non-federated Matrix-Synapse Server with ID Server for internal using.
The LDAP Lookup for Mail works great. But when a user try to insert a Mailadress in his profile in Riot, there is an Error message on the Server:
http://127.0.0.1:8090/_matrix/identity/api/v1/validate/email/requestToken was requested but not implemented

And in Riot:
{"timestamp":1499097348081,"status":501,"error":"Not Implemented","exception":"io.kamax.mxisd.exception.NotImplementedException","message":"No message available","path":"/_matrix/identity/api/v1/validate/email/requestToken"} (Status 501)

Am i doing something wrong? Sorry for my noobish question.

What i am expecting: The Server is sending an email to the user, to verify the address.

**Comment by maxidor** [comment]
You're not doing something wrong, it is indeed not implemented yet but is due in the next chunck of work. I will describe it in details in an issue but basically:
- if already present in LDAP, it will simply accept the bind but also ask if the user wants to make it public. If the user clicks yes on the e-mail, it will register with the central Matrix Identity server (configurable)
- If not:
  - If the domain part is under the IS management, it will get refused and point to the administrator (as it requires LDAP change)
  - If the domain is not under IS management, it will ask if it should be made public:
    - If yes, it will redirect to a public Matrix server
    - If not, it just gets denied.

**Comment by Kleingeldprinz** [comment]
Thank you for your answer. It helps much!
