### ISSUE TITLE
Unable to add email address

### ISSUE THREAD

**Issue by anishvarghese** [kamax-io/mxisd#20]
**While Adding a mail address to my account getting error as follows**

```
{"timestamp":1501833776376,"status":501,"error":"Not Implemented","exception":"io.kamax.mxisd.exception.NotImplementedException","message":"No message available","path":"/_matrix/identity/api/v1/validate/email/requestToken"} (Status 501)
OK
```

**Comment by maxidor** [comment]
This is expected, mxisd is read-only and you won't be able to add an e-mail for now.
It also doesn't matter as the e-mail should already be present in LDAP, so for the purpose of identity, it would still be found on lookup.

I am still thinking how to do this... stay tuned.

**Comment by maxidor** [comment]
@anishvarghese A first implementation has been done, that blindly accept mappings, without publishing them anywhere, see #23 

For the fully fledged handling, which is still in progress, see #22
