### ISSUE TITLE
Add valid use cases for mxisd on the README

### ISSUE THREAD

**Issue by maxidor** [kamax-io/mxisd#21]
mxisd use cases are not always obvious, especially given the fog/instability surrounding Identity in the Matrix spec/ecosystem.

To ensure users understand the purpose of mxisd and an Identity Server in general, valid use cases should be documented.

**Comment by doofy** [comment]
Hi @maxidor. I want to give you some input from my usecase: I run a private riot+synapse+mxisd for my institue. The university has a general LDAP and all employees have accounts there except a few external ones. mxisd bind to the ldap with the users credentials. the users login with their email address.  I use the given username from the email address for the login. mxisd fetches the full name from ldap and sets up the user account on synapse. I wrote a little script that bulk invites all known employees into a readonly channel sothat riot/synapse can built the "known users" table for every user. With that each employee can login with their trusted LDAP account and find people on our riot by searching their names.

**Comment by maxidor** [comment]
@doofy some parts of what you say worries me, as you seem to confuse mxisd and the ldap authenticator for synapse.
mxisd does *NOT* perform any authentication of users, mxisd does *NOT* create user account or profile.
mxisd only does one thing: be 3PID->MXID public directory.

**Comment by doofy** [comment]
@maxidor sorry max my rambling seems to have gotten a bit out of hand. I was trying to give you a complete description about _my_ usecase. If you want I can try again and be more clear about it. Otherwise I will accept to have failed in contributing to this ticket. no hard feelings :)

**Comment by maxidor** [comment]
I appreciate you wanting to show me your use case, and I am very much interested into it, but you give mxisd roles it cannot have, so I am puzzle how you actually use it?

**Comment by maxidor** [comment]
@doofy Still interested :)

**Comment by maxidor** [comment]
Good enough for now with the latest doc enhancements
