### ISSUE TITLE
[FEATURE] Add support for Auth via PAM

### ISSUE THREAD

**Issue by r3pek** [kamax-io/mxisd#36]
Just as a feature request.

**Comment by maxidor** [comment]
After looking more into this, I can't find a library which is any good or still actively maintained to integrate to PAM.

I'm thinking calling a command with username/password as args/env might be best at this point, which in turn could integrate with PAM.
@r3pek what do you think?

**Comment by r3pek** [comment]
@maxidor should be doable and looks like a simple solution

**Comment by maxidor** [comment]
@r3pek I've create #58 to hold the generic concept. Some idea on what the output of the command should look like would be idea, knowing that we would want the same info as in [the REST provider](https://github.com/kamax-io/mxisd/blob/master/docs/backends/rest.md#authentication).
The real question is: JSON seems highly unlikely, so what could we use?

**Comment by r3pek** [comment]
I think that's complicating it too much (the command line part). Just make it return 0/1 in case of success/fail and adjust the java part from that.
Also, try not to pass the user/password as parameters as that way something monitoring the processes can see them, pass them as env vars to the program.

**Comment by maxidor** [comment]
Using #58 to track progress, marking this as duplicate for the sake of clarity.
