### ISSUE TITLE
Explain Local Sessions

### ISSUE THREAD

**Issue by Rohithzr** [kamax-io/mxisd#46]
Hello

Referencing to the guide here [local-sessions-only](https://github.com/kamax-io/mxisd/blob/30260af1f2d4acd41c45363ae07cb9b8b7638fda/docs/sessions/3pid.md#local-sessions-only)

when adding the given config for sessions. I am getting the following error:

Steps: 
1. Register using xyz@gmail.com
2. Gets a mail with the link :
```
https://idigid.com/_matrix/identity/api/v1/validate/email/submitToken?sid=1513801081449&client_secret=F3S....&token=82...
```
3. The link returns 302 to this link
```
https://vastri.in/#/register?client_secret=OOFb1...&hs_url=https%3A%2F%2Fidigid.com&is_url=https%3A%2F%2Fidigid.com&session_id=tnyW...
```
this page now opens the same register page with the error as here
https://imgur.com/a/rAasj

What could be I be doing wrong?

**Comment by maxidor** [comment]
Riot relies on a undocumented API to handle the "return link" from registration.
That exchange is not documented anywhere and I could never get an answer on how to make it work.
So you're not doing anything wrong: it is just not supported.

**Comment by Rohithzr** [comment]
Ah.. I see
What i want to achieve is that the email verification token generated on my domain and not matrix.org. Is there any way it can be done at the moment?

**Comment by maxidor** [comment]
well it seems you do get the email verification from your domain, since the link in the email starts with `https://idigid.com/`. The question is what did you do between 2. and 3. ? Did you get a second email?

**Comment by Rohithzr** [comment]
> Did you get a second email?
Yes, from matrix.org that takes me to matrix.org website to validate the token

**Comment by maxidor** [comment]
Then it seems you didn't configure the local session properly, else you would not get a second email.

**Comment by Rohithzr** [comment]
can you guide me? that is what I was trying to setup when I reached this particular issue.

**Comment by maxidor** [comment]
Could you send me your config file **in direct message on Matrix** please? you can find me in #mxisd:kamax.io

**Comment by maxidor** [comment]
Can't seem to find an issue with this. If this happens again, please re-open this issue and make sure to include the log for the time period.

**Comment by Rohithzr** [comment]
this wasn't an issue but needed help with my config
