### ISSUE TITLE
Does not support directory lookup with Authorization header

### ISSUE THREAD

**Issue by krombel** [kamax-io/mxisd#65]
When triggering `/_matrix/client/r0/user_directory/search` where mxisd should handle that request I get the following error:
```json
{
    "errcode":"M_INCOMPLETE_REQUEST",
    "error":"Required String parameter 'access_token' is not present",
    "success":false
}
```
This lets me assume, that the `Authorization` header, where riot defaults to right now, is not implemented yet.

**Comment by maxidor** [comment]
Are you using master branch or something? or is that in the latest release?

**Comment by krombel** [comment]
I am using release 0.6.1.

**Comment by maxidor** [comment]
I meant of Riot

**Comment by maxidor** [comment]
Breaks on develop, will fix so next tagged release of Riot doesn't break

**Comment by maxidor** [comment]
Labeling as bug since [header authorization is in the spec](https://kamax.io/matrix/api/client_server/unstable.html#client-authentication) so we should support it.
