### ISSUE TITLE
Make usage of vector.im/matrix.org IS opt-in

### ISSUE THREAD

**Issue by maxidor** [kamax-io/mxisd#76]
Due to increase privacy risks using the New Vector Identity servers, we need to make their usage opt-in rather than opt-out.

Reasons for this choice:
- Cloudfare is now used in front of all their traffic and doing TLS offloading, potentially leaving all private data readable by Cloudfare, a USA-based company.
- ~~New Vector has not yet created a non-profit Matrix Foundation several months after receiving a $5M investment with unknown share-holders despite their promises.~~ New Vector will not create a non-profit structure in the foreseeable future ([Source](https://github.com/matrix-org/matrix-doc/pull/1240#discussion_r188451709)).
- New Vector's Privacy Policy allow sharing of such information with a very broad panel of potential companies/people.
- Riot, the main Matrix client, is [vulnerable to PRISM](https://github.com/nylira/prism-break/issues/1936#issuecomment-384700587).
- Riot Android/iOS sends the entire contact list emails and phone numbers to the Identity server without explicit consent from the user, which would be forwarded to New Vector servers (matrix.org) by default if usage is not opt-in.
- Matrix.org has no public privacy policy (easily?) found on its website.

**Comment by maxidor** [comment]
Done in 4f9fd42

**Comment by julianfoad** [comment]
Re. the last point "no public privacy policy (easily?) found" on matrix.org, in the initial comment. Now, at the bottom of the matrix.org home page is a link "Legal" which leads to a list of a few pages, the first one of which is "Privacy Notice" leading to https://matrix.org/docs/guides/privacy_notice.html

So I would say that point can be struck out now.

**Comment by maxidorius** [comment]
The issue has been closed, so the text is kept as-is of the historical reasons why it was so. The point struck above is one that was struck before the issue was closed. I don't plan on editing this issue any further.
