### ISSUE TITLE
LDAP backend invitation 

### ISSUE THREAD

**Issue by Gribou** [kamax-io/mxisd#84]
When the LDAP backend is used, a user's search for a new invitation to join a room is only done on the LDAP. Mxisd concidered that there is no need to send an email. But if the guest user did not connect before to the synapse server, the synapse notifications do not start either. Is there a way for an email to be sent if:
The user is found in the LDAP but not present in the Synapse database (homeserver.db)?

**Comment by maxidor** [comment]
> The user is found in the LDAP but not present in the Synapse database (homeserver.db)

This is totally out of scope for a basic Matrix Identity server, and pretty much out of scope of mxisd as it would require a special and specific integration with synapse. It is very much possible to do but it would require a very strong and good reason (to benefit the community at large) to do so.

Enrollment in Matrix at a corporate level is more a management/communication task than a technical one.

**Comment by Gribou** [comment]
I understand the point of view, indeed it will facilitate the adoption of matrix at the level of a large company. In this sense, the use of an LDAP for user authentication is perfect. I just wanted to go a little further. I'm going to look at how to achieve my goals, probably by making code adjustments or by develloping an additional module.
Any case, thank you very much for  your great work.

**Comment by Gribou** [comment]
Thanks for thoses informations.
