### ISSUE TITLE
Proxy 3pid registration requests to a different Identity server

### ISSUE THREAD

**Issue by slipeer** [kamax-io/mxisd#9]
It would be nice to have the opportunity to configure proxy 3pid assign requests to preffered Identity server (specified in config).

It will be useful when user wants assign additional 3pid not listed in LDAP.

**Comment by maxidor** [comment]
Something like that is already planned.

Currently mxisd enforce email as a 3PID but the next iteration will not enforce any 3PID type and let each resolver (LDAP, DNS, Root IS) handle it.

Once #10 has been implemented, this will follow.

**Comment by maxidor** [comment]
Phone numbers and bulk lookup have been implemented, give a try to latest trunk

**Comment by maxidor** [comment]
This issue is about sending a 3PID mapping request to another writable IS.
Totally missread this from the start.... It's not implemented.

**Comment by maxidor** [comment]
This now has landed in commit b46d047.

Release [v0.3.0-beta.1](https://github.com/kamax-io/mxisd/releases/tag/v0.3.0-beta.1) and newer will contain this features.
